source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

#abstract_target 'js-notepad' do
#    pod 'JavaScriptCoreBrowserObjectModel'
#    target 'iOS'
#    #target 'macOS'
#    #target 'tvOS'
#end

def shared_pods
    pod 'JavaScriptCoreBrowserObjectModel', :path => '..'
end
target 'iOS' do
    platform :ios, '9.0'
    shared_pods
end
#target 'macOS' do
#    platform :osx, '10.10'
#    shared_pods
#end
#target 'tvOS' do
#    platform :tvos, '9.0'
#    shared_pods
#end
